//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DurakIhlalTespitSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arac_cezalı
    {
        public string ID { get; set; }
        public string plaka { get; set; }
        public string gun { get; set; }
        public string ay { get; set; }
        public string yıl { get; set; }
    }
}
