//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DurakIhlalTespitSistemi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DurakIhlalTespitiEntities1 : DbContext
    {
        public DurakIhlalTespitiEntities1()
            : base("name=DurakIhlalTespitiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arac_cezalı> Arac_cezalı { get; set; }
        public virtual DbSet<AracBilgi> AracBilgis { get; set; }
        public virtual DbSet<Kamera_bilgi> Kamera_bilgi { get; set; }
        public virtual DbSet<Yetkili_Bilgi> Yetkili_Bilgi { get; set; }
    }
}
