//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DurakIhlalTespitSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kamera_bilgi
    {
        public string Kamera_kodu { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Cadde { get; set; }
        public string Arıza_durum { get; set; }
    }
}
