//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DurakIhlalTespitSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yetkili_Bilgi
    {
        public string Yetkili_kodu { get; set; }
        public string Yetkili_adı { get; set; }
        public string Yetkili_soyad { get; set; }
        public string Yetkili_parola { get; set; }
        public string Yetkili_sube { get; set; }
    }
}
